version: '3.7'

services:
  web:
    build:
      context: ./
      dockerfile: dockerfile
    image: fantasy-points:v1
    container_name: fantasy-points
    environment:
      - OPCACHE_ENABLED=0
      - XDEBUG_ENABLED=1
    volumes:
      - type: bind
        source: ./
        target: /var/www/html
    ports:
      - 7011:80

